/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visuales;

import Clases_De_Proyecto.Candidato;
import Clases_De_Proyecto.Elecc;
import Clases_De_Proyecto.Facultad;
import Base_de_Datos.Gestion;
import Clases_De_Proyecto.Universidad;
import Utiles.Bloqueo;
import Utiles.Entero;
import Utiles.Tupla;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Joan Manuel
 */
public class Agregar_candidatos extends javax.swing.JFrame {

    private Elecc E;
    private Gestion G;
    private Universidad U;
    private boolean candidatos_extra;
    private boolean cerrar;
    private Vector<Candidato> V_cand;
    private String nombre_anterior = "";
    
    public Agregar_candidatos(Elecc e, Universidad U, boolean X){
        initComponents();
        this.setLocationRelativeTo(null);
        G = new Gestion();
        this.E = e;
        this.U = U;
        V_cand = new Vector<>();
        
        actualizar_lista();
        this.setTitle("Elección "+ U.getNombre() + " " + G.devolver_nombre(e) + " " + e.getAnno()+": Agregar candidatos");
        cerrar = true;
        
        candidatos_extra = X;
        if(candidatos_extra && !E.getNombres_extra().isEmpty()){
            Candidatos_extra.setVisible(true);
        }
        else{
            Candidatos_extra.setVisible(false);
        }
        if(E.getTipo_de_eleccion().equals("Facultad")){
            String nombre_facultad = G.getFacultad(E.getId());
            for(int i = 0; i < U.getFacultades().size();i++){
                if(U.getFacultades().elementAt(i).getNombre().equals(nombre_facultad)){
                    añadir_carreras(U.getFacultades().elementAt(i));
                    break;
                }
            }
        }
        else{
             for(int i = 0; i < U.getFacultades().size();i++){
                    añadir_carreras(U.getFacultades().elementAt(i));
            }
        }
    }
    
    
     private void actualizar_lista(){
        
         DefaultTableModel d = new DefaultTableModel(){
             @Override
             public boolean isCellEditable(int row, int column) {
                 return false; //To change body of generated methods, choose Tools | Templates.
             }
         };
       
       jTable1 = new JTable(d);
       jScrollPane1.setViewportView(jTable1);
       
       d.addColumn("Nombre y apellidos");
       d.addColumn("Carrera");
       d.addColumn("Año académico");
              
       for(int i = 0; i < V_cand.size();i++){
           String[] X = new String[3];
           X[0] = V_cand.elementAt(i).getNombre();
           X[1] = V_cand.elementAt(i).getCarrera();
           X[2] = V_cand.elementAt(i).getAño() + "";
           
           d.addRow(X);
       }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Carrera_label = new javax.swing.JLabel();
        Ano_box = new javax.swing.JComboBox<>();
        Anadir = new javax.swing.JButton();
        Finalizar = new javax.swing.JButton();
        Nombre_candidato_label = new javax.swing.JLabel();
        Carrera_box = new javax.swing.JComboBox<>();
        Nombre_candidato = new javax.swing.JTextField();
        Ano = new javax.swing.JLabel();
        Candidatos_extra = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(11, 26, 241));
        setIconImage(getIconImage());
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0)));

        Carrera_label.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Carrera_label.setForeground(new java.awt.Color(0, 0, 0));
        Carrera_label.setText("Carrera");

        Ano_box.setBackground(new java.awt.Color(51, 102, 255));

        Anadir.setBackground(new java.awt.Color(102, 102, 102));
        Anadir.setText("Agregar");
        Anadir.setBorder(null);
        Anadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AnadirMouseClicked(evt);
            }
        });

        Finalizar.setBackground(new java.awt.Color(102, 102, 102));
        Finalizar.setText("Añadir y continuar");
        Finalizar.setBorder(null);
        Finalizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FinalizarMouseClicked(evt);
            }
        });

        Nombre_candidato_label.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Nombre_candidato_label.setForeground(new java.awt.Color(0, 0, 0));
        Nombre_candidato_label.setText("Nombre del candidato");

        Carrera_box.setBackground(new java.awt.Color(204, 204, 204));
        Carrera_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Carrera_boxActionPerformed(evt);
            }
        });

        Nombre_candidato.setBackground(new java.awt.Color(204, 204, 204));
        Nombre_candidato.setToolTipText("Nombre");
        Nombre_candidato.setBorder(null);

        Ano.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Ano.setForeground(new java.awt.Color(0, 0, 0));
        Ano.setText("Año");

        Candidatos_extra.setBackground(new java.awt.Color(102, 102, 102));
        Candidatos_extra.setText("Candidatos Extra");
        Candidatos_extra.setBorder(null);
        Candidatos_extra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Candidatos_extraActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setText("Borrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nombre_candidato_label)
                            .addComponent(Nombre_candidato, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Carrera_box, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Carrera_label, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Ano, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Ano_box, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Candidatos_extra, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Anadir, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Finalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(11, 25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre_candidato_label)
                    .addComponent(Carrera_label)
                    .addComponent(Ano))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre_candidato, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Carrera_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ano_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Candidatos_extra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Anadir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Finalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AnadirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnadirMouseClicked
       
        String nombre = Nombre_candidato.getText();
        String carrera =  Carrera_box.getSelectedItem().toString();
        int anno = Integer.parseInt(Ano_box.getSelectedItem().toString());

        if(!nombre.isEmpty() && !carrera.isEmpty()){

            Candidato C = new Candidato(nombre,carrera,anno);

            boolean flag = false;
            for(int i = 0; i < Math.max(V_cand.size(), E.getNombres().size());i++){
                if(i < V_cand.size()){
                if(Candidato.comparar(C, V_cand.elementAt(i))){
                    flag = true;
                    break;
                }
                }
                if(i < E.getNombres().size()){
                if(Candidato.comparar(C, E.getNombres().elementAt(i))){
                    flag = true;
                    break;
                }
                }
            }
            

            if(flag){
                JOptionPane.showMessageDialog(null, "El candidato ya existe", "Error",JOptionPane.ERROR_MESSAGE);
            }
            else{
                V_cand.add(C);
                actualizar_lista();
            }
            
            Nombre_candidato.setText("");
            Carrera_box.setSelectedItem(0);
            Ano_box.setSelectedItem(0);
        }
        else{
            JOptionPane.showMessageDialog(null, "El campo candidato está vacío", "Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_AnadirMouseClicked

    private void FinalizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FinalizarMouseClicked

            
            for(int i = 0; i < jTable1.getRowCount(); i++){
                Candidato C = new Candidato(jTable1.getValueAt(i, 0).toString(), jTable1.getValueAt(i, 1).toString(), Integer.parseInt(jTable1.getValueAt(i, 2).toString()));
                if(candidatos_extra){
                    boolean flag2 = false;
                    for(int j = 0; j < E.getNombres_extra().size();j++){
                        if(Candidato.comparar(C, E.getNombres_extra().elementAt(j).getN1())){
                            E.getNombres_extra().elementAt(j).getN2().setEntero(1);
                            flag2=true;
                            break;
                        }
                    }
                    if(!flag2){
                        E.getNombres_extra().add(new Tupla<>(C, new Entero(1)));
                        G.agregar_candidato(C, E, 1);
                    }
                }
                else{
                    
                    E.getNombres().add(C);
                    
                    G.agregar_candidato(C, E, 0);
                }
            }
                
            Conteo_de_boletas C = new Conteo_de_boletas(E, U);
            C.setVisible(true);
            cerrar = false;
            this.dispose();

    }//GEN-LAST:event_FinalizarMouseClicked

    private void Carrera_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Carrera_boxActionPerformed
        annadir_annos();
    }//GEN-LAST:event_Carrera_boxActionPerformed

    private void Candidatos_extraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Candidatos_extraActionPerformed
        Bloqueo BLO = new Bloqueo(this);
        Agregar_extra AE = new Agregar_extra(E, true, BLO);
        AE.setVisible(true);
        
    }//GEN-LAST:event_Candidatos_extraActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        if(cerrar){
        Principal P = new Principal();
        P.setVisible(true);  
        }
    }//GEN-LAST:event_formWindowClosed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        V_cand.remove(jTable1.getSelectedRow());
        actualizar_lista();
    }//GEN-LAST:event_jButton1ActionPerformed
private void annadir_annos(){
       borrar_todo();
       String carrera = Carrera_box.getSelectedItem().toString();
       int year = G.getAnno(carrera, U.getNombre());
       for(int i = 1; i <= year; i++){
           Ano_box.addItem(i + "");
       }
    }
 private void añadir_carreras(Facultad F){
        for(int i = 0; i < F.getCarreras().size();i++){
            Carrera_box.addItem(F.getCarreras().elementAt(i).getNombre());
        }
    }
     private void borrar_todo(){
         Ano_box.removeAllItems();
     }
     
     @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/eleccion.png"));
        return retValue;

    }
    
    
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Anadir;
    private javax.swing.JLabel Ano;
    private javax.swing.JComboBox<String> Ano_box;
    private javax.swing.JButton Candidatos_extra;
    private javax.swing.JComboBox<String> Carrera_box;
    private javax.swing.JLabel Carrera_label;
    private javax.swing.JButton Finalizar;
    private javax.swing.JTextField Nombre_candidato;
    private javax.swing.JLabel Nombre_candidato_label;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
