package Visuales;

import Base_de_Datos.Gestion;
import Utiles.Sonido;
import Operaciones.Operaciones_de_boletas;
import java.util.Vector;
import Clases_De_Proyecto.*;
import Utiles.Bloqueo;
import Utiles.RadioButtonEditor;
import Utiles.RadioButtonRenderer;
import Utiles.Tupla;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JCheckBox;
import javax.swing.JRadioButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Joan Manuel
 */
public class Conteo_de_boletas extends javax.swing.JFrame {

    private final Vector<JRadioButton> vector = new Vector<JRadioButton>();
    private final Gestion G;
    private final Elecc E;
    private final Universidad U;
     private final Sonido s = new Sonido();
    boolean cerrar;
    /**
     * Creates new form NewJFrame2
     * @param E
     * @param U
     */
    public Conteo_de_boletas(Elecc E, Universidad U) {
        initComponents();

        setResizable(false);
        this.setLocationRelativeTo(null);

        vector.add(null);
        this.E = E;
        G = new Gestion();
        this.U = U;
     this.setTitle("Elecciones Estudiantiles: Elección "+ E.getUniversidad() + " " + G.devolver_nombre(E) + " " + E.getAnno()+": Proceso de Conteo de Votos");

        cerrar = true;
        
        Matricula.setText(E.getMatricula() + "");
        Votos.setText(E.getVotos() + "");

        G.actualiar_eleccion(E);
        
        Actualizar_tabla();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        Finalizar = new javax.swing.JButton();
        Annadir_candidato = new javax.swing.JButton();
        Agregar_boleta = new javax.swing.JButton();
        Cancelar_boleta = new javax.swing.JButton();
        Annadir_votos = new javax.swing.JButton();
        Estadisticas = new javax.swing.JButton();
        Matricula = new javax.swing.JLabel();
        Votos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(getIconImage());
        setMaximumSize(new java.awt.Dimension(1000, 700));
        setMinimumSize(new java.awt.Dimension(700, 450));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Finalizar.setBackground(new java.awt.Color(102, 102, 102));
        Finalizar.setText("Finalizar");
        Finalizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FinalizarMouseClicked(evt);
            }
        });
        jPanel1.add(Finalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 560, 100, -1));

        Annadir_candidato.setBackground(new java.awt.Color(102, 102, 102));
        Annadir_candidato.setText("Añadir candidato");
        Annadir_candidato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Annadir_candidatoMouseClicked(evt);
            }
        });
        jPanel1.add(Annadir_candidato, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 560, -1, -1));

        Agregar_boleta.setBackground(new java.awt.Color(102, 102, 102));
        Agregar_boleta.setText("Agregar Boleta");
        Agregar_boleta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Agregar_boletaMouseClicked(evt);
            }
        });
        jPanel1.add(Agregar_boleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 529, 200, -1));

        Cancelar_boleta.setBackground(new java.awt.Color(102, 102, 102));
        Cancelar_boleta.setText("Cancelar Última Boleta");
        Cancelar_boleta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Cancelar_boletaMouseClicked(evt);
            }
        });
        jPanel1.add(Cancelar_boleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 200, -1));

        Annadir_votos.setBackground(new java.awt.Color(102, 102, 102));
        Annadir_votos.setText("Añadir votos");
        Annadir_votos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Annadir_votosActionPerformed(evt);
            }
        });
        jPanel1.add(Annadir_votos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 530, 120, -1));

        Estadisticas.setBackground(new java.awt.Color(102, 102, 102));
        Estadisticas.setText("Estadísticas");
        Estadisticas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EstadisticasMouseClicked(evt);
            }
        });
        jPanel1.add(Estadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 530, 101, -1));

        Matricula.setBackground(new java.awt.Color(102, 102, 102));
        Matricula.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(Matricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 560, 78, 22));

        Votos.setBackground(new java.awt.Color(102, 102, 102));
        Votos.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(Votos, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 560, 78, 22));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 760, 510));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Votos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 540, 70, 20));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Matrícula");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 540, 70, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 787, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Actualizar_tabla(){
        
        borrar_vector();
        
        
        
         DefaultTableModel d = new DefaultTableModel(){
             @Override
             public boolean isCellEditable(int row, int column) {
                return column == 3 || column == 4;         
             }
         };
         
         int cont = 0;
         
         for(int i = 0; i < E.getNombres_extra().size();i++){
             if(E.getNombres_extra().elementAt(i).getN2().getEntero() == 1){
                 cont++;
             }
         }
         
         Object[][] OBJ = new Object[E.getNombres().size() + cont][5];
    
        for(int i = 0; i < E.getNombres().size(); i++){
            OBJ[i][0] = E.getNombres().elementAt(i).getNombre();
            OBJ[i][1] = E.getNombres().elementAt(i).getCarrera();
            OBJ[i][2] = E.getNombres().elementAt(i).getAño();
            vector.add(new JRadioButton("", false));
            OBJ[i][3] = vector.lastElement();
            vector.add(new JRadioButton("", false));
            OBJ[i][4] = vector.lastElement();
        }
        int Cont = 0;
        for(int i = 0; i < E.getNombres_extra().size(); i++){
            if(E.getNombres_extra().elementAt(i).getN2().getEntero() == 1){
            int j = Cont + E.getNombres().size();
            Cont++;
            OBJ[j][0] = E.getNombres_extra().elementAt(i).getN1().getNombre();
            OBJ[j][1] = E.getNombres_extra().elementAt(i).getN1().getCarrera();
            OBJ[j][2] = E.getNombres_extra().elementAt(i).getN1().getAño();
            vector.add(new JRadioButton("", false));
            OBJ[j][3] = vector.lastElement();
            vector.add(new JRadioButton("", false));
            OBJ[j][4] = vector.lastElement();
            }
        }
        
        
       Tabla = new JTable(d);
       d.setDataVector(OBJ, new Object[]{
           "Nombre","Carrera","Año","Voto por miembro","Voto por presidente"
       });
       
       Tabla.setFont(new Font("arial", Font.BOLD, 14));
       Tabla.setRowHeight(30);
       Tabla.setShowGrid(true);
       
       Tabla.getColumn("Voto por miembro").setCellRenderer(
        new RadioButtonRenderer());
       Tabla.getColumn("Voto por miembro").setCellEditor(
        new RadioButtonEditor(new JCheckBox()));
       Tabla.getColumn("Voto por presidente").setCellRenderer(
        new RadioButtonRenderer());
       Tabla.getColumn("Voto por presidente").setCellEditor(
        new RadioButtonEditor(new JCheckBox()));
       
       jScrollPane1.setViewportView(Tabla);
       
    }
    
    
    
    
    private void Annadir_votosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Annadir_votosActionPerformed
        Bloqueo BLO = new Bloqueo(this);
        Agregar_extra AE = new Agregar_extra(E, false, BLO);
          AE.setVisible(true);
    }//GEN-LAST:event_Annadir_votosActionPerformed

    private void Cancelar_boletaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cancelar_boletaMouseClicked
        if (!E.getBoletas_guardadas().isEmpty()){
            E.setVotos(E.getVotos()-1);
            Operaciones_de_boletas.Cancelar_ultima_boleta(E);
            Votos.setText(E.getVotos() + "");

        }
        else {
            JOptionPane.showMessageDialog(null, "No hay boletas guardadas", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Cancelar_boletaMouseClicked

    private void EstadisticasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EstadisticasMouseClicked
        Bloqueo BLO = new Bloqueo(this);
        Estadisticas mostrarInfo = new Estadisticas(E, BLO);
        mostrarInfo.setVisible(true);
        mostrarInfo.getButton().setVisible(false);
    }//GEN-LAST:event_EstadisticasMouseClicked

    private void Agregar_boletaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Agregar_boletaMouseClicked
        if (E.getVotos() > E.getMatricula() - 1) {
            JOptionPane.showMessageDialog(null, "Los votos exceden a la matrícula", "Error", JOptionPane.ERROR_MESSAGE);
        }
        E.setVotos(E.getVotos()+1);
        Boleta B = crear_boleta();
        Operaciones_de_boletas.guardar_boleta(B, E);
        Operaciones_de_boletas.limpiar_candidatos_extras(E);
       Sonido sound= new Sonido();
       Votos.setText(E.getVotos() + "");
        sound.sonido("audio");
        Actualizar_tabla();
    }//GEN-LAST:event_Agregar_boletaMouseClicked

    private void Annadir_candidatoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Annadir_candidatoMouseClicked
        Agregar_candidatos AC = new Agregar_candidatos(E, U, true);
        AC.setVisible(true);
        cerrar = false;
        this.dispose();
    }//GEN-LAST:event_Annadir_candidatoMouseClicked

    private void FinalizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FinalizarMouseClicked
        new Estadisticas(E).setVisible(true);
        cerrar = false;
        this.dispose();
    }//GEN-LAST:event_FinalizarMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        if(cerrar){
        Principal P = new Principal();
        P.setVisible(true);
        }
    }//GEN-LAST:event_formWindowClosed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        Votos.setText(E.getVotos() + "");
    }//GEN-LAST:event_formWindowGainedFocus


    private Boleta crear_boleta() {
        Vector<Tupla<Candidato, Tupla<Boolean, Boolean>>> V = new Vector<>();
        V.add(new Tupla(null, new Tupla(null, null)));

        for (int i = 0; i < E.getNombres().size(); i++) {
            int j = i + 1;
            V.add(new Tupla(E.getNombres().elementAt(i), new Tupla(vector.elementAt(j * 2 - 1).isSelected(), vector.elementAt(j * 2).isSelected())));

        }
        int C = 0;
        for (int i = 0; i < E.getNombres_extra().size(); i++) {
            if(E.getNombres_extra().elementAt(i).getN2().getEntero()==1){
            int j = E.getNombres().size() + 1 + C;
            C++;
            V.add(new Tupla(E.getNombres_extra().elementAt(i).getN1(), new Tupla(vector.elementAt(j * 2 - 1).isSelected(), vector.elementAt(j * 2).isSelected())));
            }
        }
        switch (E.getTipo_de_eleccion()) {
            case "Residencia" -> {
                return new Boleta(V, 5);
            }
            case "Facultad" -> {
                return new Boleta(V, 7);
            }
            case "Universidad" -> {
                return new Boleta(V, 9);
            }
            default -> {
            return null;
            }
        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar_boleta;
    private javax.swing.JButton Annadir_candidato;
    private javax.swing.JButton Annadir_votos;
    private javax.swing.JButton Cancelar_boleta;
    private javax.swing.JButton Estadisticas;
    private javax.swing.JButton Finalizar;
    private javax.swing.JLabel Matricula;
    private javax.swing.JTable Tabla;
    private javax.swing.JLabel Votos;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void borrar_vector() {
        vector.clear();

        vector.add(null);
    }


    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/eleccion.png"));
        return retValue;

    }

    public javax.swing.JButton getButton1() {
        return Estadisticas;
    }

    public javax.swing.JButton getButton2() {
        return Cancelar_boleta;
    }

    public javax.swing.JButton getButton3() {
        return Finalizar;
    }

    public javax.swing.JButton getButton4() {
        return Annadir_candidato;
    }

    public javax.swing.JButton getButton5() {
        return Agregar_boleta;
    }
    

}
