/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visuales;

import Base_de_Datos.Gestion;
import Clases_De_Proyecto.*;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
/**
 *
 * @author Joan Manuel
 */
public class Principal extends javax.swing.JFrame {

    private final Gestion G;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        G = new Gestion();   
   this.setLocationRelativeTo(null);
        setTitle("Eleciones Estudiantiles");
          }
    
    
    public void rellenar_lista(){
        
        Lista_de_universidades.removeAllItems();
        /* Lista_de_universidades.setBackground(new Color(51,102,255));*/
        
        G.getVector_universidades().forEach(e -> {
            Lista_de_universidades.addItem(e);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Agregar_Universidad = new javax.swing.JButton();
        Editar_Universidad = new javax.swing.JButton();
        Comenzar_elecciones = new javax.swing.JButton();
        Lista_de_universidades = new javax.swing.JComboBox<>();
        Elecciones = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Agregar_Universidad.setBackground(new java.awt.Color(102, 102, 102));
        Agregar_Universidad.setText("Agregar Universidad");
        Agregar_Universidad.setBorder(null);
        Agregar_Universidad.setPreferredSize(new java.awt.Dimension(121, 25));
        Agregar_Universidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregar_UniversidadActionPerformed(evt);
            }
        });
        jPanel1.add(Agregar_Universidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 150, -1));

        Editar_Universidad.setBackground(new java.awt.Color(102, 102, 102));
        Editar_Universidad.setText("Editar Universidad");
        Editar_Universidad.setBorder(null);
        Editar_Universidad.setPreferredSize(new java.awt.Dimension(121, 25));
        Editar_Universidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Editar_UniversidadActionPerformed(evt);
            }
        });
        jPanel1.add(Editar_Universidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 150, -1));

        Comenzar_elecciones.setBackground(new java.awt.Color(102, 102, 102));
        Comenzar_elecciones.setText("Comenzar Elecciones");
        Comenzar_elecciones.setBorder(null);
        Comenzar_elecciones.setPreferredSize(new java.awt.Dimension(121, 25));
        Comenzar_elecciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Comenzar_eleccionesMouseClicked(evt);
            }
        });
        jPanel1.add(Comenzar_elecciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 105, 150, -1));

        Lista_de_universidades.setBackground(new java.awt.Color(51, 102, 255));
        Lista_de_universidades.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(Lista_de_universidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 74, 550, -1));

        Elecciones.setBackground(new java.awt.Color(102, 102, 102));
        Elecciones.setText("Elecciones");
        Elecciones.setBorder(null);
        Elecciones.setPreferredSize(new java.awt.Dimension(121, 25));
        Elecciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EleccionesActionPerformed(evt);
            }
        });
        jPanel1.add(Elecciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 150, -1));

        jLabel1.setBackground(new java.awt.Color(51, 102, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestor de Elecciones");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 557, 35));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/feu2.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 210, 230));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Desarrollado en la Universidad de Las Tunas por la carrera:  ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 390, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Ingeniería Informática ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Eric Michel Villavicencio Reyes");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Joan Manuel Molina Gomez");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Autores:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Agregar_UniversidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregar_UniversidadActionPerformed
        Nueva_Universidad NU = new Nueva_Universidad();
        NU.setVisible(true);
        dispose();
    }//GEN-LAST:event_Agregar_UniversidadActionPerformed

    private void Editar_UniversidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Editar_UniversidadActionPerformed
        try{
        
        String nombre = Lista_de_universidades.getSelectedItem().toString();          
        Nueva_Universidad NU = new Nueva_Universidad(nombre);
        NU.setVisible(true);
        dispose();
        }catch(NullPointerException e){
                         JOptionPane.showMessageDialog(null, "No hay universidades");
        }
    }//GEN-LAST:event_Editar_UniversidadActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        rellenar_lista();
    }//GEN-LAST:event_formWindowGainedFocus

    private void Comenzar_eleccionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Comenzar_eleccionesMouseClicked
        try{
        if(Lista_de_universidades.getSelectedItem() == null|| Lista_de_universidades.getItemCount()==0){
            return;
        }
        String universidad = Lista_de_universidades.getSelectedItem().toString();
        Universidad U = G.crear_universidad(universidad);
        Tipo_elecciones tp = new Tipo_elecciones(U);
        tp.setVisible(true);
        this.dispose();
        }catch(NullPointerException e){
             JOptionPane.showMessageDialog(null, "No hay universidades");
        }
    }//GEN-LAST:event_Comenzar_eleccionesMouseClicked

    private void EleccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EleccionesActionPerformed
        Gestor_de_Elecciones GE = new Gestor_de_Elecciones();
        GE.setVisible(true);
        dispose();
    }//GEN-LAST:event_EleccionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/eleccion.png"));
        return retValue;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar_Universidad;
    private javax.swing.JButton Comenzar_elecciones;
    private javax.swing.JButton Editar_Universidad;
    private javax.swing.JButton Elecciones;
    private javax.swing.JComboBox<String> Lista_de_universidades;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
