/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visuales;

import Clases_De_Proyecto.Elecc;
import Base_de_Datos.Gestion;
import Clases_De_Proyecto.Universidad;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.Calendar;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author SchWarZer
 */
public class Tipo_elecciones extends javax.swing.JFrame {

    private final Gestion G;
    private final Universidad universidad;
    private boolean cerrar;
    /**
     * Creates new form
     * @param universidad
     */
    public Tipo_elecciones(Universidad universidad) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Elecciones Estudiantiles: Selección de Proceso Electoral de: "+universidad.getNombre());
        
        G = new Gestion();
        this.universidad = universidad;
       
        setResizable(false);
        Seleccion_lugar.setVisible(false);
        cerrar = true;
        
        Annos.removeAllItems();
            
            Calendar C = Calendar.getInstance();
            int a = C.get(Calendar.YEAR);
            
            for(int i = a; i <= a+10; i++){
                Annos.addItem(i + "");
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        Seleccion_tipo = new javax.swing.JComboBox<>();
        Aceptar = new javax.swing.JButton();
        Seleccion_lugar = new javax.swing.JComboBox<>();
        Annos = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(getIconImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel.setBackground(new java.awt.Color(153, 153, 153));
        Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0)));
        Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Seleccion_tipo.setBackground(new java.awt.Color(51, 102, 255));
        Seleccion_tipo.setForeground(new java.awt.Color(102, 102, 255));
        Seleccion_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Universidad", "Facultad", "Residencia" }));
        Seleccion_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Seleccion_tipoActionPerformed(evt);
            }
        });
        Panel.add(Seleccion_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 120, 37));

        Aceptar.setBackground(new java.awt.Color(102, 102, 102));
        Aceptar.setText("aceptar");
        Aceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AceptarMouseClicked(evt);
            }
        });
        Panel.add(Aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 249, 98, 40));

        Seleccion_lugar.setBackground(new java.awt.Color(51, 102, 255));
        Panel.add(Seleccion_lugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 12, 248, 37));

        Annos.setBackground(new java.awt.Color(51, 102, 255));
        Panel.add(Annos, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 12, 167, 37));

        jRadioButton1.setText("Elecciones por representatnte");
        Panel.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        getContentPane().add(Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Seleccion_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Seleccion_tipoActionPerformed
        
          
         switch (Seleccion_tipo.getSelectedItem().toString()) {
            case "Universidad" -> {
                Seleccion_lugar.setVisible(false);
                jRadioButton1.setVisible(true);
                Seleccion_lugar.removeAllItems();
                
            }
            case "Facultad" -> {
                Seleccion_lugar.setVisible(true);
                jRadioButton1.setVisible(false);
                Seleccion_lugar.removeAllItems();
                Vector<String> facultades = G.devolver_facultades(universidad.getNombre());
                for(int i = 0; i < facultades.size();i++){
                    Seleccion_lugar.addItem(facultades.elementAt(i));
                }
            }
            case "Residencia" -> {
                Seleccion_lugar.setVisible(true);
                jRadioButton1.setVisible(false);
                Seleccion_lugar.removeAllItems();
                Vector<String> residencias = G.devolver_residencias(universidad.getNombre());
                if(residencias.isEmpty()){
                    Seleccion_lugar.setVisible(false);
                    break;
                }
                for(int i = 0; i < residencias.size();i++){
                    Seleccion_lugar.addItem(residencias.elementAt(i));
                }
            }
            default -> {
            }
        }
    }//GEN-LAST:event_Seleccion_tipoActionPerformed

    private void AceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AceptarMouseClicked

 
            try{
            
            String anno = Annos.getSelectedItem().toString();
            
         String tipo_eleccion = Seleccion_tipo.getSelectedItem().toString();
            int id = 0;
            if(tipo_eleccion.equals("Universidad")){
                id = G.obtenerID(universidad.getNombre());
            }
            
            else{
                id = G.obtenerID(universidad.getNombre(), tipo_eleccion, Seleccion_lugar.getSelectedItem().toString());
            }
            int matricula = 0;
            if(tipo_eleccion.equals("Universidad")&& !jRadioButton1.isSelected()){
                matricula = universidad.getMatricula();
            }
            else{
                matricula = G.getMatricula(id, tipo_eleccion);
            }
            if(jRadioButton1.isSelected()){
                  matricula = Integer.parseInt(JOptionPane.showInputDialog("Cantidad de representantes"));
            }
            Elecc e = new Elecc(tipo_eleccion, anno, id, matricula, universidad.getNombre(),jRadioButton1.isSelected());
           if(G.revisar_eleccion_repetida(e)){
                JOptionPane.showMessageDialog(null, "Ya existen unas elecciones con estas características ", "Error", JOptionPane.ERROR_MESSAGE);
                return;
           }
            
                G.agregar_eleccion(anno, tipo_eleccion, id,jRadioButton1.isSelected(),matricula);
            
            cerrar = false;
            Agregar_candidatos agregarCandidatos = new Agregar_candidatos(e, universidad, false);
            agregarCandidatos.setVisible(true);
        this.dispose();
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Error ", "Error", JOptionPane.ERROR_MESSAGE);
        }
                        
            
    }//GEN-LAST:event_AceptarMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        if(cerrar){
        Principal P = new Principal();
        P.setVisible(true);
        }
    }//GEN-LAST:event_formWindowClosed

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/eleccion.png"));
        return retValue;

    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JComboBox<String> Annos;
    private javax.swing.JPanel Panel;
    private javax.swing.JComboBox<String> Seleccion_lugar;
    private javax.swing.JComboBox<String> Seleccion_tipo;
    private javax.swing.JRadioButton jRadioButton1;
    // End of variables declaration//GEN-END:variables
}
